ARM: versatile: define empty debug_ll_io_init() for no-MMU
No-MMU configured targets have no definition for debug_ll_io_init().
Not all machines use this and it will only be required if CONFIG_DEBUG_LL
is enabled.

But when compiling for a target that uses it and it is configured for
no-MMU (!CONFIG_MMU), for example the versatile machine, you will get:

  CC      arch/arm/mach-versatile/versatile_dt.o
arch/arm/mach-versatile/versatile_dt.c: In function ‘versatile_map_io’:
arch/arm/mach-versatile/versatile_dt.c:283:2: error: implicit declaration of function ‘debug_ll_io_init’ [-Werror=implicit-function-declaration]
  debug_ll_io_init();
  ^

Fix by adding a macro for it to the !CONFIG_MMU path in map.h.

Signed-off-by: Greg Ungerer <gerg@kernel.org>
Reviewed-by: Vladimir Murzin <vladimir.murzin@arm.com>